GDJ86-DH-MJ-ES/mall

- src/main/resources/application.properties
> Log Setting 추가

- src/main/resources/application.properties
> 동현) application.properties 수정

- src/main/java/com/example/mall/controller/StaffController.java
> 동현) StaffController 생성

- src/main/java/com/example/mall/controller/CustomerController.java
> 동현) CustomerController 생성

- src/main/java/com/example/mall/controller/BoardController.java
> 동현) BoardController 생성

- src/main/java/com/example/mall/interceptor/CustomerInterceptor.java
- src/main/java/com/example/mall/interceptor/OffInterceptor.java
- src/main/java/com/example/mall/interceptor/StaffInterceptor.java
은서 ) Customer/Staff/Off interceptor class 생성
> 은서 ) Customer/Staff/Off interceptor class 생성

- src/main/java/com/example/mall/mapper/AddressMapper.java
- src/main/java/com/example/mall/mapper/AddressMapper.xml
- src/main/java/com/example/mall/mapper/BoardMapper.java
- src/main/java/com/example/mall/service/AddressService.java
- src/main/java/com/example/mall/service/BoardService.java
- src/main/java/com/example/mall/service/CartService.java
- src/main/java/com/example/mall/service/CategoryService.java
- src/main/java/com/example/mall/service/CustomerService.java
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/java/com/example/mall/service/LoginService.java
- src/main/java/com/example/mall/service/PaymentService.java
- src/main/java/com/example/mall/service/StaffService.java
> 문정) Mapper, Service 수정

- src/main/java/com/example/mall/MallApplication.java
- src/main/java/com/example/mall/interceptor/CustomerInterceptor.java
- src/main/java/com/example/mall/interceptor/OffInterceptor.java
- src/main/java/com/example/mall/interceptor/StaffInterceptor.java
은서) MallApplication - interceptor registry 설정 및 각 인터셉터 주석 상세기술수정
> 은서) MallApplication - interceptor registry 설정 및 각 인터셉터 주석 상세기술수정

- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/StaffMapper.java
- src/main/java/com/example/mall/mapper/StaffMapper.xml
- src/main/java/com/example/mall/service/StaffService.java
- src/main/java/com/example/mall/vo/Staff.java
> 동현）staff 기능 추가

- src/main/java/com/example/mall/vo/Page.java
> 은서) Page Vo 생성

- src/main/java/com/example/mall/controller/HomeController.java
- src/main/webapp/WEB-INF/view/inc/footer.jsp
- src/main/webapp/WEB-INF/view/inc/header.jsp
- src/main/webapp/WEB-INF/view/inc/staffHeader.jsp
- src/main/webapp/WEB-INF/view/inc/staffLeftMenu.jsp
- src/main/webapp/WEB-INF/view/off/goodsOne.jsp
- src/main/webapp/WEB-INF/view/off/join.jsp
- src/main/webapp/WEB-INF/view/off/login.jsp
- src/main/webapp/WEB-INF/view/staff/addStaff.jsp
- src/main/webapp/WEB-INF/view/staff/staff.jsp
> 문정) 부트스트랩 템플릿 추가

- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/StaffMapper.java
- src/main/java/com/example/mall/mapper/StaffMapper.xml
- src/main/java/com/example/mall/service/StaffService.java
> 동현) removeStaff 기능 추가

- src/main/java/com/example/mall/controller/CartController.java
- src/main/java/com/example/mall/mapper/CartMapper.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/service/CartService.java
은서) Cart - selectCartListByCustomerId 구현
> 은서) Cart - selectCartListByCustomerId 구현

- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/StaffMapper.java
- src/main/java/com/example/mall/mapper/StaffMapper.xml
- src/main/java/com/example/mall/service/StaffService.java
- src/main/java/com/example/mall/util/TeamColor.java
TeamColor 기능 추가
customerList 조회 기능 추가
> 동현) TeamColor 기능 추가

- src/main/java/com/example/mall/controller/HomeController.java
- src/main/java/com/example/mall/controller/LoginController.java
- src/main/webapp/WEB-INF/view/off/login.jsp
> 문정) 로그인 수정

- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/StaffMapper.java
- src/main/java/com/example/mall/mapper/StaffMapper.xml
- src/main/java/com/example/mall/service/StaffService.java
> 동현) removeCustomerByStaff 기능 추가

- src/main/java/com/example/mall/controller/CartController.java
- src/main/java/com/example/mall/mapper/CartMapper.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/mapper/CustomerMapper.java
- src/main/java/com/example/mall/mapper/CustomerMapper.xml
- src/main/java/com/example/mall/service/CartService.java
- src/main/java/com/example/mall/service/CustomerService.java
은서) customer.login(mapper,service 구현), Cart-add, remove 구현
> 은서) customer.login(mapper,service 구현), Cart-add, remove 구현

- src/main/java/com/example/mall/mapper/CustomerMapper.xml
은서) CustomerMapper : staff.login() 쿼리 수정
> 은서) CustomerMapper : staff.login() 쿼리 수정

- src/main/java/com/example/mall/mapper/CartMapper.java
- src/main/java/com/example/mall/mapper/CustomerMapper.java
- src/main/java/com/example/mall/mapper/CustomerMapper.xml
은서) CustomerMapper 쿼리 수정, CustomerMapper, CartMapper 접근제어자 변경
> 은서) CustomerMapper 쿼리 수정, CustomerMapper, CartMapper 접근제어자 변경

- src/main/java/com/example/mall/controller/HomeController.java
- src/main/java/com/example/mall/controller/LoginController.java
- src/main/webapp/WEB-INF/view/customer/cart.jsp
> 문정) login 수정

- src/main/java/com/example/mall/controller/HomeController.java
- src/main/java/com/example/mall/controller/LoginController.java
- src/main/webapp/WEB-INF/view/inc/header.jsp
- src/main/webapp/WEB-INF/view/inc/staffLeftMenu.jsp
- src/main/webapp/WEB-INF/view/off/login.jsp
- src/main/webapp/WEB-INF/view/off/template.jsp
> 문정) template 수정

- src/main/java/com/example/mall/controller/CartController.java
- src/main/java/com/example/mall/mapper/CustomerMapper.xml
- src/main/java/com/example/mall/service/CartService.java
- src/main/webapp/WEB-INF/view/customer/getCartList.jsp
은서) login customer 쿼리 정정, getCartList(前 Cart.jsp) 수정중
> 은서) login customer 쿼리 정정, getCartList(前 Cart.jsp) 수정중

- src/main/java/com/example/mall/controller/LoginController.java
- src/main/webapp/WEB-INF/view/off/loginC.jsp
- src/main/webapp/WEB-INF/view/off/loginS.jsp
고객용, 직원용 테스트용으로 로그인화면 구현(완성 후 삭제예정)
> 은서 ) 테스트용 로그인 화면(off/loginC, off/loginS) 구현

- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/StaffMapper.java
- src/main/java/com/example/mall/mapper/StaffMapper.xml
- src/main/java/com/example/mall/service/StaffService.java
- src/main/webapp/WEB-INF/view/inc/staffLeftMenu.jsp
- src/main/webapp/WEB-INF/view/staff/addStaff.jsp
- src/main/webapp/WEB-INF/view/staff/getCustomerListByStaff.jsp
getStaffList.jsp
getCustomerListByStaff.jsp
removeStaff
removeCustomerByStaff jsp에 기능 추가
> 동현) getStaffList.jsp

- src/main/java/com/example/mall/controller/CartController.java
- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/interceptor/CustomerInterceptor.java
- src/main/java/com/example/mall/interceptor/OffInterceptor.java
- src/main/java/com/example/mall/interceptor/StaffInterceptor.java
- src/main/java/com/example/mall/mapper/CartMapper.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/service/CartService.java
- src/main/webapp/WEB-INF/view/customer/getCartList.jsp
- src/main/webapp/WEB-INF/view/customer/getCartListByChecked.jsp
- src/main/webapp/WEB-INF/view/customer/payResult.jsp
- src/main/webapp/WEB-INF/view/off/loginC.jsp
은서 ) 장바구니, 조회, 결제하기 , 결제완료 MVC구현 (V미완), author 수정 및 addPayment 및 getPayResult 구현중
> 은서 ) 장바구니, 조회, 결제하기 , 결제완료 MVC구현 (V미완), author 수정 및 addPayment 및 getPayResult 구현중

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/controller/LoginController.java
- src/main/webapp/WEB-INF/view/off/home.jsp
- src/main/webapp/WEB-INF/view/off/login.jsp
문정) login 유효성 검사 추가, GoodsList 수정
> 문정) login 유효성 검사 추가, GoodsList 수정

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
> 문정) getGoodsOne 수정

- src/main/java/com/example/mall/controller/BoardController.java
- src/main/webapp/WEB-INF/view/inc/header.jsp
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
- src/main/webapp/WEB-INF/view/off/home.jsp
문정) header.jsp : 로그아웃 연결, getGoodsOne: 후기 추가
> 문정) header.jsp : 로그아웃 연결, getGoodsOne: 후기 추가

- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/StaffMapper.java
- src/main/java/com/example/mall/mapper/StaffMapper.xml
- src/main/java/com/example/mall/service/StaffService.java
- src/main/webapp/WEB-INF/view/inc/staffHeader.jsp
- src/main/webapp/WEB-INF/view/inc/staffLeftMenu.jsp
- src/main/webapp/WEB-INF/view/staff/addStaff.jsp
- src/main/webapp/WEB-INF/view/staff/getCustomerListByStaff.jsp
- src/main/webapp/WEB-INF/view/staff/getStaffList.jsp
getCustomerListByStaff 페이징 기능 추가
> 동현) getCustomerListByStaff 페이징 기능 추가

- src/main/webapp/WEB-INF/view/inc/staffLeftMenu.jsp
> 동현) staffLeftMenu 이슈 해결

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
> 문정) getGoodsOne 수정중

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
> 문정) goodsOne 수정중

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/mapper/PaymentMapper.java
- src/main/java/com/example/mall/mapper/PaymentMapper.xml
- src/main/java/com/example/mall/service/PaymentService.java
addPay(payment)+addOrder(Orders)+removeCart(cart) 트랜잭션처리 테스트 완료 및 필요없는
디버깅코드 삭제 , getCartList 수정중
> 은서)addPay(payment)+addOrder(Orders)+removeCart(cart) 트랜잭션처리 테스트 완료 및 필요없는 디버깅코드 삭제 , getCartList 수정중

- src/main/java/com/example/mall/controller/BoardController.java
- src/main/java/com/example/mall/mapper/BoardMapper.java
- src/main/java/com/example/mall/mapper/BoardMapper.xml
- src/main/java/com/example/mall/service/BoardService.java
- src/main/webapp/WEB-INF/view/staff/getBoardListByStaff.jsp
- src/main/webapp/WEB-INF/view/staff/getGoodsList.jsp
boardList 조회
removeBoard 기능 추가
> 동현) staff 전용 boardList 관리페이지 작성

- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
> 문정) getGoodsOne.jsp 수정

- src/main/java/com/example/mall/controller/BoardController.java
- src/main/java/com/example/mall/mapper/BoardMapper.java
- src/main/java/com/example/mall/mapper/BoardMapper.xml
- src/main/java/com/example/mall/service/BoardService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
> 문정) 후기 작성, 삭제 추가

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/PaymentMapper.xml
- src/main/java/com/example/mall/service/PaymentService.java
- src/main/webapp/WEB-INF/view/customer/getPaymentList.jsp
은서 ) paymentList, selectPayInfoListByPaymentNo 고객용, 직원용 구현 완료, 뷰 수정필요
> 은서 ) paymentList, selectPayInfoListByPaymentNo 고객용, 직원용 구현 완료, 뷰 수정필요

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/staff/addGoods.jsp
- src/main/webapp/WEB-INF/view/staff/getGoodsListByStaff.jsp
GoodsMapper deleteGoods Query 수정
getGoodsList 기능 추가
serchWord 기능 추가
removeGoods 기능 추가
> 동현) 오전 작업 Commit

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/PaymentMapper.java
- src/main/java/com/example/mall/mapper/PaymentMapper.xml
- src/main/java/com/example/mall/service/PaymentService.java
- src/main/webapp/WEB-INF/view/customer/getPaymentList.jsp
은서) Payment관련 직원/고객 쿼리 구현 및 테스팅 완료, 고객용 PaymentList view 틀 완성
> 은서) Payment관련 직원/고객 쿼리 구현 및 테스팅 완료, 고객용 PaymentList view 틀 완성

- src/main/java/com/example/mall/controller/AddressController.java
- src/main/java/com/example/mall/mapper/AddressMapper.java
- src/main/java/com/example/mall/mapper/AddressMapper.xml
- src/main/java/com/example/mall/service/AddressService.java
- src/main/webapp/WEB-INF/view/customer/getAddressList.jsp
- src/main/webapp/WEB-INF/view/off/home.jsp
> 문정) 배송지 추가

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/PaymentMapper.xml
- src/main/webapp/WEB-INF/view/staff/getPaymentList.jsp
> 문정) staff - paymentList 수정중

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/webapp/WEB-INF/view/off/home.jsp
> 문정) /home : category 수정

- src/main/java/com/example/mall/controller/CustomerController.java
- src/main/java/com/example/mall/mapper/CartMapper.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/mapper/CustomerMapper.java
- src/main/java/com/example/mall/mapper/CustomerMapper.xml
- src/main/java/com/example/mall/service/CartService.java
- src/main/java/com/example/mall/service/CustomerService.java
- src/main/java/com/example/mall/service/PaymentService.java
- src/main/java/com/example/mall/vo/Cart.java
- src/main/webapp/WEB-INF/view/customer/getCustomerOne.jsp
- src/main/webapp/WEB-INF/view/customer/modifyCustomerPw.jsp
- src/main/webapp/WEB-INF/view/off/addCustomer.jsp
은서) modifyCustomerPw, deleteCustomer(트랜잭션) 구현 및 테스트 완료, 
deleteCart동적쿼리수정, 
paymentService 에서 addPayment-(3) 에서 deleteCart 파라미터 부분 수정, 
Cart Vo 오타 수정, 
addCustomer 작업중
> 은서) modifyCustomerPw, deleteCustomer 구현 및 테스트 완료, addCustomer 작업중

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/service/CustomerService.java
- src/main/webapp/WEB-INF/view/customer/getPaymentList.jsp
- src/main/webapp/WEB-INF/view/inc/pagination/customerGetCartList.jsp
> 은서 ) pagination 알고리즘 변경

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
> 문정) goodsList - 수정

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/controller/StaffController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/staff/addGoods.jsp
- src/main/webapp/WEB-INF/view/staff/modifyGoods.jsp
> 동현) goodsModify 작업중..

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/home.jsp
> 문정) goodsController 수정

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/home.jsp
> 문정)/hoem - goodsList 수정

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/staff/getGoodsListByStaff.jsp
- src/main/webapp/WEB-INF/view/staff/modifyGoods.jsp
modifyGoods에서 goodsFile 수정부터..
> 동현) modifyGoods 기능 추가

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/controller/LoginController.java
- src/main/java/com/example/mall/mapper/GoodsFileMapper.java
- src/main/java/com/example/mall/mapper/GoodsFileMapper.xml
- src/main/java/com/example/mall/service/GoodsFileService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
- src/main/webapp/WEB-INF/view/off/login.jsp
> 문정) goodsOne 이미지 수정

- src/main/webapp/WEB-INF/view/off/login.jsp
- src/main/webapp/WEB-INF/view/staff/getBoardListByStaff.jsp
- src/main/webapp/WEB-INF/view/staff/getCustomerListByStaff.jsp
- src/main/webapp/WEB-INF/view/staff/getPaymentList.jsp
> 문정) pagination 수정

- src/main/webapp/WEB-INF/view/off/addCustomer.jsp
> 문정) 회원가입폼 수정중

- src/main/java/com/example/mall/controller/BoardController.java
- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
- src/main/webapp/WEB-INF/view/off/home.jsp
> 문정) board 수정중

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
- src/main/webapp/WEB-INF/view/off/home.jsp
> 문정) customer 수정중

- src/main/java/com/example/mall/controller/GoodsController.java
- src/main/java/com/example/mall/mapper/GoodsMapper.xml
- src/main/java/com/example/mall/service/GoodsService.java
- src/main/webapp/WEB-INF/view/off/getGoodsOne.jsp
- src/main/webapp/WEB-INF/view/staff/getPaymentList.jsp
> 문정) board등 수정중

- src/main/java/com/example/mall/controller/PaymentController.java
> 문정) paymentList 수정중

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/PaymentMapper.java
- src/main/java/com/example/mall/mapper/PaymentMapper.xml
- src/main/java/com/example/mall/service/PaymentService.java
- src/main/webapp/WEB-INF/view/customer/getCartListByChecked.jsp
- src/main/webapp/WEB-INF/view/customer/getPaymentList.jsp
- src/main/webapp/WEB-INF/view/staff/getPaymentList.jsp
[은서 ) selectPayInfoListByPaymentNo 쿼리 Limit 1 추가 및 반환타입 Map으로 수정하여 하나의](https://github.com/GDJ86-DH-MJ-ES/mall/commit/df76704c23c6578514f7d3f43606f66164787e0b) 
PaymentNo에 따른 Order정보가 나오도록 서비스, 매퍼 수정
> 은서 ) selectPayInfoListByPaymentNo 쿼리 Limit 1 추가 및 반환타입 Map으로 수정하여 하나의   PaymentNo에 따른 Order정보가 나오도록 서비스, 매퍼 수정

- src/main/webapp/WEB-INF/view/customer/getAddressList.jsp
- src/main/webapp/WEB-INF/view/customer/getCartList.jsp
- src/main/webapp/WEB-INF/view/customer/getCartListByChecked.jsp
- src/main/webapp/WEB-INF/view/customer/getCustomerOne.jsp
- src/main/webapp/WEB-INF/view/customer/getPaymentList.jsp
- src/main/webapp/WEB-INF/view/customer/modifyCustomerPw.jsp
- src/main/webapp/WEB-INF/view/customer/payResult.jsp
- src/main/webapp/WEB-INF/view/inc/customerHeader.jsp
- src/main/webapp/WEB-INF/view/off/home.jsp
[은서 ) 고객 관련 view 전반적으로 수정, home 부분 헤더 고정](https://github.com/GDJ86-DH-MJ-ES/mall/commit/bbe1e0369321d84bcbba50c9bcf7ec6fe2bbfdad)
> 은서 ) 고객 관련 view 전반적으로 수정, home 부분 헤더 고정

- src/main/webapp/WEB-INF/view/inc/customerHeader.jsp
[은서 ) 고객 헤더 css 수정](https://github.com/GDJ86-DH-MJ-ES/mall/commit/922ce6307b92f6bab52bdd6f43a8aa6195e4fc26)
> 은서 ) 고객 헤더 css 수정

- src/main/java/com/example/mall/controller/PaymentController.java
- src/main/java/com/example/mall/mapper/CartMapper.xml
- src/main/java/com/example/mall/mapper/PaymentMapper.java
- src/main/java/com/example/mall/mapper/PaymentMapper.xml
- src/main/java/com/example/mall/service/PaymentService.java
> 은서 ) paymentNo : ordersNo : 상세정보 1:多:多 적용하여 paymentMapper 쿼리 수정 및 컨트롤러

- src/main/java/com/example/mall/controller/StatisticalController.java
- src/main/java/com/example/mall/mapper/StatisticalMapper.java
- src/main/java/com/example/mall/mapper/StatisticalMapper.xml
- src/main/java/com/example/mall/service/StatisticalService.java
- src/main/resources/static/js/demo/chart-area-demo.js
- src/main/webapp/WEB-INF/view/staff/statistical.jsp
> 문정) 통계 수정중

- src/main/resources/static/js/demo/chart-area-demo.js
- src/main/resources/static/js/demo/chart-pie-demo.js
- src/main/webapp/WEB-INF/view/staff/statistical.jsp
> 동현) 그래프 수정중

- src/main/java/com/example/mall/controller/CategoryController.java
- src/main/java/com/example/mall/mapper/CategoryMapper.java
- src/main/java/com/example/mall/mapper/CategoryMapper.xml
- src/main/java/com/example/mall/service/CategoryService.java
- src/main/webapp/WEB-INF/view/staff/getCategoryList.jsp
> 문정) 카테고리 수정
